version: "3.3"

services:
  web:
    build: .
    restart: always
    command: sh -c "python3 manage.py collectstatic --no-input && python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      gunicorn -b 0.0.0.0:8000 core.wsgi --reload"
    volumes:
        - ./:/app
        - ./media:/app/media/
        - ./static:/app/static/
    ports:
        - "8000:8000"
    depends_on:
        - pgdb

  pgdb:
    image: postgres:motionweb
    restart: always
    container_name: pgdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=motionweb
<<<<<<< HEAD
      - POSTGRES_USER=motionweb
      - POSTGRES_PASSWORD=motionweb_llc
=======
      - POSTGRES_USER=motionweb_user
      - POSTGRES_PASSWORD=motionweb_123
>>>>>>> f5f8660d9d1657ca454b37abef37d1305a4acf41

  nginx:
      image: linuxserver/swag
      restart: always
      environment:
          - PUID=1000
          - PGID=1000
          - TZ=Asia/Bishkek
          - URL=motion-web.io
          - SUBDOMAINS=api
          - VALIDATION=http
          - ONLY_SUBDOMAINS=true
          - STAGING=false
      depends_on:
          - web
      ports:
          - "80:80"
          - "443:443"
      volumes:
          - ./nginx/nginx.conf:/config/nginx/site-confs/default
          - ./media:/app/media
          - lets:/config/keys/
          - ./static:/app/static

volumes:
  postgres_data:
  lets:
