# Generated by Django 4.0.3 on 2022-04-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motionApp', '0004_order_description_alter_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='url_project',
        ),
        migrations.AddField(
            model_name='order',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/file', verbose_name='Загрузить файл'),
        ),
    ]
