# Generated by Django 4.0.3 on 2022-05-16 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motionApp', '0006_remove_order_upload_order_url_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Vacancy',
        ),
    ]
