# Generated by Django 4.0.3 on 2022-05-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motionApp', '0007_rename_jobs_vacancy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='description',
            new_name='description_ru',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='name_ru',
        ),
        migrations.RemoveField(
            model_name='createstaff',
            name='name',
        ),
        migrations.RemoveField(
            model_name='createstaff',
            name='position',
        ),
        migrations.AddField(
            model_name='createstaff',
            name='name_en',
            field=models.CharField(default=1, max_length=20, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createstaff',
            name='name_ru',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='createstaff',
            name='position_en',
            field=models.CharField(default=1, max_length=50, verbose_name='Position'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createstaff',
            name='position_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='order',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='order',
            name='name_en',
            field=models.CharField(default=1, max_length=200, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
