# Generated by Django 4.0.3 on 2022-05-16 10:29

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motionApp', '0008_rename_description_order_description_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='name_ru',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='name',
        ),
        migrations.AddField(
            model_name='feedback',
            name='name_en',
            field=models.CharField(default=1, max_length=20, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Введите описание'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='name_en',
            field=models.CharField(default=1, max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
    ]
