# Generated by Django 3.2.9 on 2022-05-28 05:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motionApp', '0009_rename_name_feedback_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createstaff',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='order',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Фотография'),
        ),
    ]
