# Generated by Django 3.2.9 on 2022-05-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motionApp', '0010_auto_20220528_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createstaff',
            name='image',
            field=models.ImageField(upload_to='image/person', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.ImageField(upload_to='image/poduct', verbose_name='Фотография'),
        ),
    ]
