# Generated by Django 4.0.3 on 2022-05-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(verbose_name='URL видео')),
                ('title', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Видео клиента',
                'verbose_name_plural': 'Видео клиента',
            },
        ),
        migrations.RenameModel(
            old_name='OurClient',
            new_name='Review',
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
