# Generated by Django 4.0.3 on 2022-05-01 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0002_clientvideo_rename_ourclient_review_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Наш клиент', 'verbose_name_plural': 'Нашы клиенты'},
        ),
    ]
