# Generated by Django 4.0.3 on 2022-05-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0004_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв клиента', 'verbose_name_plural': 'Отзывы клиентов'},
        ),
    ]
