# Generated by Django 4.0.3 on 2022-05-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0005_alter_review_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientvideo',
            name='title',
        ),
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.AddField(
            model_name='clientvideo',
            name='title_en',
            field=models.TextField(default=1, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientvideo',
            name='title_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='review',
            name='name_en',
            field=models.CharField(default=1, max_length=50, verbose_name='Full name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='name_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Полное имя'),
        ),
        migrations.AddField(
            model_name='review',
            name='title_en',
            field=models.TextField(default=1, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='title_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
