# Generated by Django 4.0.3 on 2022-03-30 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='FeedbackLink',
        ),
    ]
