# Generated by Django 4.0.3 on 2022-04-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_rename_feedback_feedbacklink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbacklink',
            old_name='question',
            new_name='mail',
        ),
    ]
