# Generated by Django 4.0.3 on 2022-04-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_rename_mail_feedbacklink_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/client', verbose_name='Фотография')),
                ('name', models.CharField(max_length=50, verbose_name='Фамилия и Имя')),
                ('title', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
