# Generated by Django 4.0.3 on 2022-05-01 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_ourclient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourclient',
            options={'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратные связи'},
        ),
    ]
