# Generated by Django 4.0.3 on 2022-05-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_alter_ourclient_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacklink',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ourclient',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ourclient',
            name='title',
        ),
        migrations.AddField(
            model_name='feedbacklink',
            name='name_en',
            field=models.CharField(default=1, max_length=30, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedbacklink',
            name='name_ru',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='ourclient',
            name='name_en',
            field=models.CharField(default=1, max_length=50, verbose_name='Full name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourclient',
            name='name_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия и Имя'),
        ),
        migrations.AddField(
            model_name='ourclient',
            name='title_en',
            field=models.TextField(default=1, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourclient',
            name='title_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
