# Generated by Django 4.0.3 on 2022-05-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0011_remove_feedbacklink_name_remove_ourclient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourclient',
            name='name_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Полное имя'),
        ),
    ]
