# Generated by Django 4.0.3 on 2022-05-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0012_alter_ourclient_name_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacklink',
            name='budget',
            field=models.CharField(default=1, max_length=50, verbose_name='Бюджет'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedbacklink',
            name='phone',
            field=models.CharField(default=1, max_length=30, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
