# Generated by Django 3.2.9 on 2022-05-28 05:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0013_feedbacklink_budget_alter_feedbacklink_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourclient',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Фотография'),
        ),
    ]
